services:
  stella-runner:
    build:
      context: ./modules/stella_runner
      dockerfile: Dockerfile
    image: 381492108418.dkr.ecr.eu-north-1.amazonaws.com/bimefy/stella-runner:latest-test
    container_name: stella-runner

    env_file:
      - .env
    volumes:
      - ./content:/stella_vslam_examples/content
      - /tmp:/tmp 
      - /var/run/docker.sock:/var/run/docker.sock
  # stella-vslam:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: 381492108418.dkr.ecr.eu-north-1.amazonaws.com/bimefy/stella-vslam:latest-test
  #   container_name: stella-vslam
  #   entrypoint: /bin/bash
  #   stdin_open: true
  #   tty: true       
  #   volumes:
  #     - ./content:/stella_vslam_examples/content
  #     - /tmp:/tmp 
  # stella_vslam_viewer:
  #   build:
  #     context: ./modules/socket_viewer
  #     dockerfile: Dockerfile
  #   image: 381492108418.dkr.ecr.eu-north-1.amazonaws.com/bimefy/stella-vslam-viewer:latest
  #   container_name: stella-vslam-viewer
  #   network_mode: host
  #   tty: true
  #   stdin_open: true
  #   restart: unless-stopped
