services:
  stella-vslam:
    image: 381492108418.dkr.ecr.eu-north-1.amazonaws.com/bimefy/stella-vslam:latest
    build:
      context: .
      dockerfile: Dockerfile.cuda
    platform: linux/amd64
    container_name: stella-vslam
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - OMP_MAX_ACTIVE_LEVELS=2
    volumes:
      - ./content:/stella_vslam_examples/content
      - /tmp:/tmp 
  stella_vslam_viewer:
     image: 381492108418.dkr.ecr.eu-north-1.amazonaws.com/bimefy/stella-vslam-viewer:latest
     container_name: stella-vslam-viewer
     network_mode: host
     restart: unless-stopped
  stella-runner:
    build:
      context: ./modules/stella_runner
      dockerfile: Dockerfile
    image: 381492108418.dkr.ecr.eu-north-1.amazonaws.com/bimefy/stella-runner:latest
    container_name: stella-runner
    env_file:
      - .env
    volumes:
      - /tmp:/tmp 
      - /var/run/docker.sock:/var/run/docker.sock