# Equirectangular model for RICOH THETA S

Camera:
  name: "RICOH THETA S 960" 
  setup: "monocular"
  model: "equirectangular"
 
  fps: 25.0
  cols: 7680
  rows: 3840
 
  color_order: "RGB"

Preprocessing:
  min_size: 800
  mask_rectangles:
    - [0.0, 1.0, 0.0, 0.1]
    - [0.0, 1.0, 0.84, 1.0]
    - [0.0, 0.2, 0.7, 1.0]
    - [0.8, 1.0, 0.7, 1.0]

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 4
  ini_fast_threshold: 12
  min_fast_threshold: 7

Mapping:
  backend: "g2o"
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.9
  num_covisibilities_for_landmark_generation: 10
  num_covisibilities_for_landmark_fusion: 10
  residual_deg_thr: 0.4

Tracking:
  backend: "g2o"

LoopDetector:
  backend: "g2o"
  enabled: true
  reject_by_graph_distance: true
  min_distance_on_graph: 30

GraphOptimizer:
  min_num_shared_lms: 100

GlobalOptimizer:
  thr_neighbor_keyframes: 50

System:
  map_format: "msgpack"
  num_grid_cols: 24
  num_grid_rows: 6

SocketPublisher:
  server_uri: "http://localhost:3000"