 Camera:
  name: "Insta360 X4"
  setup: "monocular"
  model: "equirectangular"
 
  fps: 25.0
  cols: 7680
  rows: 3840
 
  color_order: "RGB"
 
Preprocessing:
  min_size: 800
  mask_rectangles:
    - [0.0, 1.0, 0.0, 0.1]
    - [0.0, 1.0, 0.84, 1.0]
    - [0.0, 0.2, 0.7, 1.0]
    - [0.8, 1.0, 0.7, 1.0]
 
Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 10
 
Mapping:
  backend: "g2o"
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.95
  num_covisibilities_for_landmark_generation: 20
  num_covisibilities_for_landmark_fusion: 20
  residual_deg_thr: 0.4
 
Tracking:
  backend: "g2o"
  reloc_distance_threshold: 10
  init_retry_threshold_time: 10
  enable_temporal_keyframe_only_tracking: true
  enable_relocalization: true
 
LoopDetector:
  backend: "g2o"
  enabled: true
  reject_by_graph_distance: true
  min_distance_on_graph: 50
 
GraphOptimizer:
  min_num_shared_lms: 200
 
GlobalOptimizer:
  thr_neighbor_keyframes: 100
 
System:
  map_format: "sqlite3"
  num_grid_cols: 96
  num_grid_rows: 48

Relocalizer:
  search_neighbor: true

KeyframeInserts:
  min_distance: 10
  min_interval: 10
  wait_for_local_bundle_adjustment: true

SocketPublisher:
  server_uri: "http://localhost:3000"