services:
  stella-runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: 381492108418.dkr.ecr.eu-north-1.amazonaws.com/bimefy/stella-runner:latest
    container_name: stella-runner
    platform: linux/amd64
    env_file:
      - .env
    volumes:
      - /tmp:/tmp 
      - /var/run/docker.sock:/var/run/docker.sock